services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql
    env_file:
      - ./docker-compose-mysql.env
    ports:
      - 3306:3306
    volumes:
      - ../.environment/mysql:/docker-entrypoint-initdb.d
