services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: server /data --console-address ":9001"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./docker-compose-minio.env
    volumes:
      - ../.environment/minio/data:/data
      - ../.environment/minio/config:/root/.minio
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
